<a href="https://colab.research.google.com/github/fillerInk/colab_notebooks/blob/master/ML_Workshop_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
x = np.array([1,2,3])

In [5]:
type(x)

numpy.ndarray

In [0]:
y = np.array([1,2,3])

In [0]:
z = np.dot(x,y)

In [10]:
type(z)

numpy.int64

In [9]:
print(z)

14


In [11]:
print(np.square(x))

[1 4 9]


In [12]:
x

array([1, 2, 3])

In [0]:
a = np.array([[2,3,4],[4,5,6]])

In [15]:
type(a)

numpy.ndarray

In [16]:
a.shape

(2, 3)

In [30]:
a.reshape(3,2)

array([[2, 3],
       [4, 4],
       [5, 6]])

In [0]:
b = np.array([[1,2,3],[2,3,4],[3,7,8]])

In [34]:
print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.flags)

[[1 2 3]
 [2 3 4]
 [3 7 8]]
2
(3, 3)
9
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [38]:
a.reshape(2,3)

print(np.matmul(a,b))

[[20 41 50]
 [32 65 80]]


In [19]:
q = np.ones((2,3))
print(q)

r = np.zeros((3,4))
print(r)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
w = np.random.random((2,2))
print(w)

[[0.6472603  0.91749029]
 [0.20991388 0.96405334]]


In [22]:
w.ndim

2