<a href="https://colab.research.google.com/github/fillerInk/colab_notebooks/blob/master/MP_Neuron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Loading Data


In [0]:
import sklearn.datasets
import numpy as np

In [0]:
breast_cancer = sklearn.datasets.load_breast_cancer()

In [0]:
x = breast_cancer.data
y = breast_cancer.target

In [6]:
print(x)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [7]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

In [8]:
len(y)

569

In [9]:
len(x)

569

In [10]:
x[1]

array([2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02, 7.864e-02,
       8.690e-02, 7.017e-02, 1.812e-01, 5.667e-02, 5.435e-01, 7.339e-01,
       3.398e+00, 7.408e+01, 5.225e-03, 1.308e-02, 1.860e-02, 1.340e-02,
       1.389e-02, 3.532e-03, 2.499e+01, 2.341e+01, 1.588e+02, 1.956e+03,
       1.238e-01, 1.866e-01, 2.416e-01, 1.860e-01, 2.750e-01, 8.902e-02])

In [11]:
print(x.shape)

(569, 30)


In [12]:
print(y.shape)

(569,)


In [0]:
import pandas as pd

In [0]:
data = pd.DataFrame(breast_cancer.data, columns=breast_cancer.feature_names)

In [0]:
data['class'] = breast_cancer.target

In [16]:
data.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...    worst texture  worst perimeter  worst area  \
0                 0.07871  ...            17.33           184.60      2019.0   
1                 0.05667  ...            23.41           158.80      1956.0   
2                 0.05999  ...            25.53           152.50      1709.0   
3                 0.09744  ...            26.50            98.87       567.7   
4                 0.05883  ...            16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  class  
0          0.4601                  0.11890      0  
1          0.2750                  0.08902      0  
2          0.3613                  0.08758      0  
3          0.6638                  0.17300      0  
4          0.2364                  0.07678      0  

[5 rows x 31 columns]

In [17]:
data.describe()


mean radius  mean texture  mean perimeter    mean area  \
count   569.000000    569.000000      569.000000   569.000000   
mean     14.127292     19.289649       91.969033   654.889104   
std       3.524049      4.301036       24.298981   351.914129   
min       6.981000      9.710000       43.790000   143.500000   
25%      11.700000     16.170000       75.170000   420.300000   
50%      13.370000     18.840000       86.240000   551.100000   
75%      15.780000     21.800000      104.100000   782.700000   
max      28.110000     39.280000      188.500000  2501.000000   

       mean smoothness  mean compactness  mean concavity  mean concave points  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       mean symmetry  mean fractal dimension     ...      worst texture  \
count     569.000000              569.000000     ...         569.000000   
mean        0.181162                0.062798     ...          25.677223   
std         0.027414                0.007060     ...           6.146258   
min         0.106000                0.049960     ...          12.020000   
25%         0.161900                0.057700     ...          21.080000   
50%         0.179200                0.061540     ...          25.410000   
75%         0.195700                0.066120     ...          29.720000   
max         0.304000                0.097440     ...          49.540000   

       worst perimeter   worst area  worst smoothness  worst compactness  \
count       569.000000   569.000000        569.000000         569.000000   
mean        107.261213   880.583128          0.132369           0.254265   
std          33.602542   569.356993          0.022832           0.157336   
min          50.410000   185.200000          0.071170           0.027290   
25%          84.110000   515.300000          0.116600           0.147200   
50%          97.660000   686.500000          0.131300           0.211900   
75%         125.400000  1084.000000          0.146000           0.339100   
max         251.200000  4254.000000          0.222600           1.058000   

       worst concavity  worst concave points  worst symmetry  \
count       569.000000            569.000000      569.000000   
mean          0.272188              0.114606        0.290076   
std           0.208624              0.065732        0.061867   
min           0.000000              0.000000        0.156500   
25%           0.114500              0.064930        0.250400   
50%           0.226700              0.099930        0.282200   
75%           0.382900              0.161400        0.317900   
max           1.252000              0.291000        0.663800   

       worst fractal dimension       class  
count               569.000000  569.000000  
mean                  0.083946    0.627417  
std                   0.018061    0.483918  
min                   0.055040    0.000000  
25%                   0.071460    0.000000  
50%                   0.080040    1.000000  
75%                   0.092080    1.000000  
max                   0.207500    1.000000  

[8 rows x 31 columns]

In [19]:
print(data['class'].value_counts())

1    357
0    212
Name: class, dtype: int64


In [22]:
print(breast_cancer.target_names)

['malignant' 'benign']


In [24]:
data.groupby('class').mean()

mean radius  mean texture  mean perimeter   mean area  mean smoothness  \
class                                                                           
0        17.462830     21.604906      115.365377  978.376415         0.102898   
1        12.146524     17.914762       78.075406  462.790196         0.092478   

       mean compactness  mean concavity  mean concave points  mean symmetry  \
class                                                                         
0              0.145188        0.160775             0.087990       0.192909   
1              0.080085        0.046058             0.025717       0.174186   

       mean fractal dimension           ...             worst radius  \
class                                   ...                            
0                    0.062680           ...                21.134811   
1                    0.062867           ...                13.379801   

       worst texture  worst perimeter   worst area  worst smoothness  \
class                                                                  
0          29.318208       141.370330  1422.286321          0.144845   
1          23.515070        87.005938   558.899440          0.124959   

       worst compactness  worst concavity  worst concave points  \
class                                                             
0               0.374824         0.450606              0.182237   
1               0.182673         0.166238              0.074444   

       worst symmetry  worst fractal dimension  
class                                           
0            0.323468                 0.091530  
1            0.270246                 0.079442  

[2 rows x 30 columns]

# Test Train Splitting

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
x = data.drop('class',axis=1)
y = data['class']

In [0]:
x_train, x_test, y_train, y_test = train_test_split(x,y)

In [29]:
x_train


mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
166       10.800          9.71           68.77      357.6          0.09594   
242       11.300         18.19           73.93      389.4          0.09592   
369       22.010         21.90          147.20     1482.0          0.10630   
567       20.600         29.33          140.10     1265.0          0.11780   
562       15.220         30.62          103.40      716.9          0.10480   
26        14.580         21.53           97.41      644.8          0.10540   
164       23.270         22.04          152.10     1686.0          0.08439   
324       12.200         15.21           78.01      457.9          0.08673   
246       13.200         17.43           84.13      541.6          0.07215   
263       15.610         19.38          100.00      758.6          0.07840   
371       15.190         13.21           97.65      711.8          0.07963   
529       12.070         13.44           77.83      445.2          0.11000   
152        9.731         15.34           63.78      300.2          0.10720   
471       12.040         28.14           76.85      449.9          0.08752   
327       12.030         17.93           76.09      446.0          0.07683   
428       11.130         16.62           70.47      381.1          0.08151   
145       11.900         14.65           78.11      432.8          0.11520   
83        19.100         26.29          129.10     1132.0          0.12150   
318        9.042         18.90           60.07      244.5          0.09968   
18        19.810         22.15          130.00     1260.0          0.09831   
301       12.460         19.89           80.43      471.3          0.08451   
56        19.210         18.57          125.50     1152.0          0.10530   
31        11.840         18.70           77.93      440.6          0.11090   
407       12.850         21.37           82.63      514.5          0.07551   
222       10.180         17.53           65.12      313.1          0.10610   
53        18.220         18.70          120.30     1033.0          0.11480   
178       13.010         22.22           82.01      526.4          0.06251   
25        17.140         16.40          116.00      912.7          0.11860   
17        16.130         20.68          108.10      798.8          0.11700   
376       10.570         20.22           70.15      338.3          0.09073   
..           ...           ...             ...        ...              ...   
232       11.220         33.81           70.79      386.8          0.07780   
253       17.300         17.08          113.00      928.2          0.10080   
126       13.610         24.69           87.76      572.6          0.09258   
554       12.880         28.92           82.50      514.3          0.08123   
117       14.870         16.67           98.64      682.5          0.11620   
334       12.300         19.02           77.88      464.4          0.08313   
49        13.490         22.30           86.91      561.0          0.08752   
386       12.210         14.09           78.78      462.0          0.08108   
353       15.080         25.74           98.00      716.6          0.10240   
545       13.620         23.23           87.19      573.2          0.09246   
299       10.510         23.09           66.85      334.2          0.10150   
536       14.270         22.55           93.77      629.8          0.10380   
336       12.990         14.23           84.08      514.3          0.09462   
389       19.550         23.21          128.90     1174.0          0.10100   
348       11.470         16.03           73.02      402.7          0.09076   
361       13.300         21.57           85.24      546.1          0.08582   
147       14.950         18.77           97.84      689.5          0.08138   
432       20.180         19.54          133.80     1250.0          0.11330   
69        12.780         16.49           81.37      502.5          0.09831   
560       14.050         27

In [30]:
x_test

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
418       12.700         12.17           80.88      495.0          0.08785   
226       10.440         15.46           66.62      329.6          0.10530   
385       14.600         23.29           93.97      664.7          0.08682   
281       11.740         14.02           74.24      427.3          0.07813   
142       11.430         17.31           73.66      398.0          0.10920   
179       12.810         13.06           81.29      508.8          0.08739   
405       10.940         18.59           70.39      370.0          0.10040   
282       19.400         18.18          127.20     1145.0          0.10370   
287       12.890         13.12           81.89      515.9          0.06955   
292       12.950         16.02           83.14      513.7          0.10050   
105       13.110         15.56           87.21      530.2          0.13980   
266       10.600         18.95           69.28      346.4          0.09688   
451       19.590         25.00          127.70     1191.0          0.10320   
310       11.700         19.11           74.33      418.7          0.08814   
384       13.280         13.72           85.79      541.8          0.08363   
243       13.750         23.77           88.54      590.0          0.08043   
275       11.890         17.36           76.20      435.6          0.12250   
430       14.900         22.53          102.10      685.0          0.09947   
237       20.480         21.46          132.50     1306.0          0.08355   
476       14.200         20.53           92.41      618.4          0.08931   
493       12.460         12.83           78.83      477.3          0.07372   
239       17.460         39.28          113.40      920.6          0.09812   
160       11.750         20.18           76.10      419.8          0.10890   
435       13.980         19.62           91.12      599.5          0.10600   
91        15.370         22.76          100.20      728.2          0.09200   
262       17.290         22.13          114.40      947.8          0.08999   
364       13.400         16.95           85.48      552.4          0.07937   
484       15.730         11.28          102.80      747.2          0.10430   
425       10.030         21.28           63.19      307.3          0.08117   
191       12.770         21.41           82.02      507.4          0.08749   
..           ...           ...             ...        ...              ...   
345       10.260         14.71           66.20      321.6          0.09882   
535       20.550         20.86          137.80     1308.0          0.10460   
532       13.680         16.33           87.76      575.5          0.09277   
8         13.000         21.82           87.50      519.8          0.12730   
174       10.660         15.15           67.49      349.6          0.08792   
205       15.120         16.68           98.78      716.6          0.08876   
540       11.540         14.44           74.65      402.9          0.09984   
57        14.710         21.59           95.55      656.9          0.11370   
192        9.720         18.22           60.73      288.1          0.06950   
234        9.567         15.91           60.21      279.6          0.08464   
531       11.670         20.02           75.21      416.2          0.10160   
320       10.250         16.18           66.52      324.2          0.10610   
482       13.470         14.06           87.32      546.3          0.10710   
372       21.370         15.10          141.30     1386.0          0.10010   
421       14.690         13.98           98.22      656.1          0.10310   
538        7.729         25.49           47.98      178.8          0.08098   
503       23.090         19.83          152.10     1682.0          0.09342   
381       11.040         14.93           70.67      372.7          0.07987   
526       13.460         18.75           87.44      551.1          0.10750   
565       20.130         28