<a href="https://colab.research.google.com/github/fillerInk/colab_notebooks/blob/master/Torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x = torch.ones(3,2)
print(x)
y = torch.zeros(3,2)
print(y)
z = torch.rand(3,2)
print(z)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0.6945, 0.6181],
        [0.5535, 0.0868],
        [0.9166, 0.2297]])


In [3]:
print(x.size())
print(x[:,1])
print(x[0,:])

torch.Size([3, 2])
tensor([1., 1., 1.])
tensor([1., 1.])


In [2]:
print(torch.cuda.device_count())

1


In [4]:
print(torch.cuda.device(0))
print(torch.cuda.get_device_name(0))

Tesla P4


In [0]:
cuda = torch.device('cuda:0')